### ISSUE TITLE
interactive tutorial

### ISSUE THREAD

**Issue by jqtrde** [maptime/getting-started-with-git-and-github#1]
Have you see this? https://github.com/jlord/git-it

**Comment by lyzidiamond** [comment]
I really love Git It! Most people I know who've gone through it really like it, but I have heard from some folks that it's kind of a lot at once. They tend to be the folks who are super new to any tech stuff at all, though.

**Comment by clhenrick** [comment]
@jacquestardie @lyzidiamond do y'all think we need to have our own tutorial or just some links to existing ones like git-it? I know some folks have an aversion to using the Terminal so maybe including a tutorial on the GitHub App would be useful as well.

**Comment by mapmeld** [comment]
some tutorials using the app would actually be helpful! I was setting someone up on GitHub for Windows last weekend and wasn't sure what to do because it has different words and organization from what you'd see on the command line.

**Comment by clhenrick** [comment]
@mapmeld if you find a good one add it to the README? I just updated it with a section for more in depth and interactive learning.

**Comment by lyzidiamond** [comment]
I think adding some sort of like, tips/tricks/how-tos/best practices from maptimers might be useful. I think the more stuff out there about git and GitHub from different perspectives, the better! People have tons of different workflows, too, so there's always more to add/do/learn. I've been meaning to adapt an email I wrote to a friend into a blog post, so maybe something like that could help? Or we could just link to existing ones. :grin:

**Comment by clhenrick** [comment]
@lyzidiamond Cool, I added links to the README for existing tutorials and other resources. I'm all for  adding a tutorial of our own too. Also, as @mapmeld suggested we should have a tutorial for how to use the GitHub App for folks who aren't comfortable with Terminal.
